remote_theme: just-the-docs/just-the-docs
title: kommand
description: Documentation for Kommand
baseurl: "/docs" # the subpath of your site, e.g. /blog
url: "https://ooflet.github.io" # the base hostname & protocol for your site, e.g. http://example.com

color_scheme: BetterDarkTheme
search_enabled: false
# Aux links for the upper right navigation
aux_links:
  "Github":
    - "https://github.com/ooflet/kommand"
footer_content: "Kommand utilises the UNC API"
<body>
<a href="https://scriptunc.org" style="height:max-content;" target="_blank">
    <img style="width: 120px;height:auto;" alt="UNC Supported Badge" src="https://scriptunc.org/badge.png"/>
</a>
</body>

